server:
  port: 6666
spring:
  application:
    name: cloud-zuul-service
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: stock8844
    pool-size: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
zuul:
  sensitive-headers: Cookie,Set-Cookie
  ignored-services: '*'
  prefix: /api
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    userService: /user/**
    stockService: /company/**
    auth: /auth/**

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${eureka.instance.hostname}:${server.port}
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.netflix: DEBUG
    com.bruin.cloud.zuul.filters: DEBUG


