server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true #prefer to use ip for client
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  datasource:
    initialization-mode: NEVER
