spring:
  profiles: eureka1
  datasource:
    initialization-mode: NEVER
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#below is the multiple configuration parameter mark, need to config the Active profile to run it separately
---
spring:
  profiles: eureka2
eureka:
  instance:
    hostname: eureka2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:8762/eureka/
server:
  port: 8762
